### ISSUE TITLE
Use Swagger to create API documentation

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#12]
Integrate Swagger to document the backend API routes, including their request parameters, responses, and error codes. Keep the documentation updated as the API evolves.

**Reference:**
- [Swagger with Express](https://dev.to/franciscomendes10866/swagger-api-documentation-in-nodejs-express-2nkd)

**Comment by Utkarsh-2005** [comment]
I would like to work on this

**Comment by swastik-apk** [comment]
@dead8309 I am keen to contribute to this project.

- Can you provide more details about the issue described?
- Which files or modules should I focus on to address this issue?
- How should I validate that the issue is fixed? Are there any specific test cases or scenarios to consider?
- How should we handle authentication and authorization in the Swagger documentation?
- Where should the Swagger setup code be placed in the project structure?
- Are there any specific standards or conventions we should follow for documenting our API endpoints?
- What is the process for updating the Swagger documentation when new endpoints are added or existing ones are modified?

P.S. : I copied the questions from ChatGPT

**Comment by Tony-ArtZ** [comment]
@swastik-apk you can follow this [guide](https://dev.to/cuongnp/swagger-nodejs-express-a-step-by-step-guide-4ob) to get started. Simply add a page which will show all the routes with their parameters and return types (all taken care by swagger package). You can also update Readme.md with the route details if you wish.

**Comment by swastik-apk** [comment]
Where can I produce the environment variables ?

**Comment by Tony-ArtZ** [comment]
@swastik-apk you can use any value for now, there is a .env.example. For mongodb you can use locally hosted server or your own deployment on ATLAS for testing. But I don't think it would be required for this issue.

**Comment by swastik-apk** [comment]
@Tony-ArtZ Ok, I think I can do this. Can you assign the issue to me?

**Comment by Tony-ArtZ** [comment]
@swastik-apk Sure ! Best of luck ! Happy hacktoberfest!

**Comment by swastik-apk** [comment]
[Swagger UI Collapsed.pdf](https://github.com/user-attachments/files/17459209/Swagger.UI.Collapsed.pdf)
[Swagger UI Expanded.pdf](https://github.com/user-attachments/files/17459210/Swagger.UI.Expanded.pdf)

@Tony-ArtZ  I have tried implementing Swagger. Tell me if I need to change anything.

**Comment by dead8309** [comment]
Looks great. Open a pr
